#!/usr/bin/env bash
# a script to create a file with cntents and trap various signals

# Create PID file
echo $$ > /var/run/myscript.pid

trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "echo I hate the kill command; rm -f /var/run/myscript.pid; exit" SIGQUIT SIGTERM

# Main loop (infinite)
while true;
do
  echo "To infinity and beyond!"
  sleep 1
done
