#!/usr/bin/env bash
# a script to create a file with cntents and trap various signals

echo $$ > /var/run/myscript.pid
while true
do
    echo "To infinity and beyond"
    trap "echo I hate the kill command" SIGTERM
    trap "echo Y U no love me?!" SIGINT
#    trap 'rm /var/run/myscript.pid; kill -15 "$$"'
done
