#!/usr/bin/env bash
# a script that manages a processs on startup

id="$#"

# copy the p[rocess to the init.d d dir
cp manage_my_process /etc/init.d/manage_my_process

if [ "$id" -ne 1 ]
then
    echo "Usage: manage_my_process {start|stop|restart}"
    exit
fi
case "$1" in
    "start")
	./manage_my_process &
	echo $$ >> /var/run/my_process.pid
	echo "manage_my_process started"
        ;;
    "stop")
	pkill -f ./manage_my_process
	shred -u /var/run/my_process.pid
	echo "manage_my_process stopped"
	;;
    "restart")
	pkill -f ./manage_my_process
	shred -u /var/run/my_process.pid
	./manage_my_process &
	echo $$ >> /var/run/my_process.pid
	echo "manage_my_process restarted"
	;;
    *)
	echo "Usage: manage_my_process {start|stop|restart}"
esac
