#!/usr/bin/env bash
# A script to modify IP addresses and the hosts file
# am trying to use awk

cp /etc/hosts ~/hosts.new
# Update hosts file
# Check for existing localhost entry
grep -q "localhost" ~/hosts.new
if [ $? -eq 0 ]; then
  # If it exists, update the entry with sed
  sed -i 's/^localhost.*/127.0.0.2 localhost/' ~/hosts.new
else
  # If not, append a new entry
  echo "127.0.0.2 localhost" >> ~/hosts.new
fi

# Check for existing facebook.com entry
grep -q "facebook.com" ~/hosts.new
if [ $? -eq 0 ]; then
  # If it exists, update the entry with sed
  sed -i 's/^facebook.com.*/8.8.8.8 facebook.com/' ~/hosts.new
else
  # If not, append a new entry
  echo "8.8.8.8 facebook.com" >> ~/hosts.new
fi

cp -f ~/hosts.new /etc/hosts
